[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kmeans"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "cuda-python",
    "torch",
]

[project.optional-dependencies]
test = [
    "pytest",
]
benchmark = [
    "cupti-python",
    "nvidia-cuda-cupti",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"flashlib_cake_kmeans" = ["manifest.json", "cuda/*.cu"]

